### ISSUE TITLE
Can someone provide a few sentences on what this does?

### ISSUE THREAD

**Issue by MikeFultonDev** [ambitus/cbexplorer#3]
I have some ideas, but would love to learn more.

**Comment by Dieter-W** [comment]
Hi Mike,
I just merged the missing information.  Now we have a README which gives you more information how it works.  This CB-Explorer goes together with the ZML repro, which defines the ZML Standard.
If you have more question let me know (wellerdiek@de.ibm.com) and we setup an call to discuss the whole functionality and the upcoming needed work.

**Comment by MikeFultonDev** [comment]
Thanks!
